avatar: /assets/icon/rdplogo.png
assets_rt: # https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/material/assets
  # 如果有cdn提高assets文件夹的加载速度,请填入地址
  # 否则留空
theme: clean # (beauty|clean)

randomimg:
  type: folder # (folder|list)
  path: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img/
  cnt: 36
  suf: webp
  list: # urls

comment:
  enable: False
  valine:
    enable: True
    appid: NLh0fhL***************-gzGzoHsz
    appkey: DSwqdjP**********pfkcB9
    placeholder: 说几句嘛qwq
  gitalk:
    enable: True
    clientID: 0549**********fe427e
    clientSecret: b31*********************************2c69ba
    repo: example.github.io
    owner: example
    admin: example
    distractionFreeMode: 'false'

pjax: True # enable pjax

appbar:
  pages:
    标签云: /tags/
    分类: /categories/
    友链: /links/
    工具集: /tools/
    关于: /about/

head_card:
  enable: True
  img: /assets/huge_icon/markdown.png
  logo: /assets/icon/rdplogo.png
  text: material theme for py-blog
  introduction: a theme with material-design
  pages:
    标签云: /tags/
    分类: /categories/
    友链: /links/
    工具集: /tools/
    关于: /about/

footer:
  enable: True
  site_create_date: 2019
  site_till_date: 2021
  icons:
    github: https://github.com/example/
    bilibili: https://space.bilibili.com/
    zhihu: https://www.zhihu.com/
    twitter: https://twitter.com/example
  lastbuild: True

drawer:
  Pages:
  - content: 标签云
    url: /tags/
    icon:
      typ: mdui # (mdui|mqii|img)
      data: bookmark_border
      color: black
  - content: 分类
    url: /categories/
    icon:
      typ: mdui
      data: book
      color: black
  - content: 友链
    url: /links/
    icon:
      typ: mdui
      data: link
      color: black
  - content: 工具集
    url: /tools/
    icon:
      typ: mdui
      data: build
      color: black
  - content: 关于
    url: /about/
    icon:
      typ: mdui
      data: person
      color: black
  - content: 订阅
    url: /atom.xml
    icon:
      typ: mdui
      data: rss_feed
      color: black
  - content: 站点地图
    url: /sitemap.xml
    icon:
      typ: mdui
      data: list
      color: black
  Catch me:
  - content: 给我写信
    url: mailto:example@example.com
    icon:
      typ: mdui
      data: email
      color: dodgerblue
  - content: 电报
    url: https://t.me/example/
    icon:
      typ: mqii
      data: telegram
      color: '#66ccff'
  - content: 推特
    url: https://twitter.com/example/
    icon:
      typ: mqii
      data: twitter
      color: rgba(29,161,242,1.00)
  - content: 哔哩哔哩
    url: https://space.bilibili.com/
    icon:
      typ: mqii
      data: bilibili
      color: '#F06292'
  - content: 网易云音乐
    url: https://music.163.com/user/home/?id=
    icon:
      typ: mqii
      data: netease-cloud-music
      color: red
  - content: 知乎
    url: https://www.zhihu.com/
    icon:
      typ: mqii
      data: zhihu
      color: '#0084ff'

  - content: Github
    url: https://github.com/example/
    icon:
      typ: mqii
      data: github
      color: black
  Links:
  - content: index
    url: https://example.com/
    icon:
      typ: img
      data: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img/avatar_2.webp
  - content: Traveling
    url: https://travellings.now.sh/
    icon:
      typ: mqii
      data: telegram
      color: '#bbb'
search:
  typ: local #(local|worker|)
  file: /pure_data.json
  api: https://blog-search.example.com/

share_menu:
  twitter: True
  weibo: True
  qq: True

busuanzi:
  enable: False

highlight:
  theme: github
